name: JS Release

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "javascript/**"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rollup globally
        run: npm install --global rollup

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package with Rollup
        working-directory: ./javascript
        run: npx rollup -c rollup.config.mjs

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
